"""
Script to help you get your correct Telegram Chat ID
"""

print("=" * 60)
print("HOW TO GET YOUR TELEGRAM CHAT ID")
print("=" * 60)
print()
print("Method 1: Using @userinfobot")
print("  1. Open Telegram")
print("  2. Search for: @userinfobot")
print("  3. Start a conversation with it")
print("  4. It will show your User ID (this is your chat ID)")
print()
print("Method 2: Using @RawDataBot")
print("  1. Open Telegram")
print("  2. Search for: @RawDataBot")
print("  3. Start a conversation")
print("  4. Send any message")
print("  5. It will reply with your chat information")
print()
print("Method 3: Check your current .env file")
print("  Your current chat ID in .env is: 8055550422")
print("  This appears to be a bot ID, not your user ID")
print()
print("=" * 60)
print("IMPORTANT:")
print("  - Chat ID should be your PERSONAL user ID (numbers)")
print("  - NOT a bot ID")
print("  - NOT a group ID (unless you want group notifications)")
print("=" * 60)
print()
print("Once you have your correct chat ID:")
print("1. Update .env file:")
print("   TELEGRAM_CHAT_ID=your_correct_chat_id")
print()
print("2. Or run: python setup_telegram.py")
print("   (and provide the correct chat ID when prompted)")

